### ISSUE TITLE
gnet 性能数据问题

### ISSUE THREAD

**Issue by jkgeekJack** [panjf2000/gnet_benchmarks#2]
![echo](https://user-images.githubusercontent.com/15207717/65373313-58939d00-dcae-11e9-9402-a32fd007a55e.png)

**Comment by panjf2000** [comment]
你是直接跑 benchmark 的脚本还是有做了一些修改？

**Comment by jkgeekJack** [comment]
我是4核的机器，GOMAXPROCS改成4了

**Comment by jkgeekJack** [comment]
改成8之后，各个请求数都下降了，标准包下降最厉害
![echo](https://user-images.githubusercontent.com/15207717/65373871-acee4b00-dcb5-11e9-9910-8ec5cd28add2.png)

**Comment by panjf2000** [comment]
忘了问是什么 OS ？Linux 还是 macOS ?

**Comment by jkgeekJack** [comment]
Linux

**Comment by panjf2000** [comment]
好的，谢谢反馈，我下午看一下。

**Comment by panjf2000** [comment]
Hello，压测脚本和最新的性能测试报告已更新：
![](https://raw.githubusercontent.com/panjf2000/gnet_benchmarks/master/results/echo_linux.png)
